---
title: "Contact helps dispreferred combinations of typological features to survive: geospatial evidence"
subtitle: "Statistical analyses"
output:
  html_document:
    toc: true
---


# Preliminaries

Packages etc:

```{r}
# required packages
require(tidyverse)
require(reshape2)
require(broom)
require(pixiedust)
require(emmeans)
require(stringr)
require(ggplot2)
require(gridExtra)
require(ggsci)
require(ggsignif)
source("pvalString_demo.R")
source("kloop.R")

# create results/tables, if it doesn't exist already
try(dir.create("../../results/tables", recursive=TRUE))
```

Theme:

```{r}
# default theme
deftheme <- function() {
    g <- theme_bw()
    #  g <- g + theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank())
    g <- g + theme(panel.grid.minor=element_blank())
    g <- g + theme(axis.text=element_text(color="black"))
    g <- g + theme(strip.text=element_text(size=10), strip.background=element_blank())
    #g <- g + theme(strip.text=element_text(size=12, hjust=0), strip.background=element_blank()  )
    g <- g + theme(text=element_text(family="Times"))
    g <- g + theme(plot.title=element_text(size=11))
    g
}
```

Prepare data:

```{r}
prep_data <- function(dataset) {
	# load data
	data <- read.csv(paste0("../../results/", dataset, "/results_combined.csv"))

	# rename "non-interacting" as "control"
	data$status <- ifelse(data$status == "non-interacting", "control", data$status)
	data$status <- factor(data$status)
	data$status <- relevel(data$status, ref="control")

	# return
	data
} 

wals <- prep_data("wals")
gram <- prep_data("grambank")
```

# Descriptive statistics

Mean sample sizes:

```{r}
round(mean(wals$N))
round(mean(gram$N))
```


# Neighborhood size sweep

```{r}
klops <- do_all_kloops(dfW = wals, dfG = gram, ks = 1:500)
source("plot_kloop_complicated.R")

wals_ideal <- which.max(klops[klops$dataset == "WALS", ]$SNR)
gram_ideal <- which.max(klops[klops$dataset == "Grambank", ]$SNR)

fullwals <- wals
fullgram <- gram

wals <- wals[wals$degree == wals_ideal, ]
gram <- gram[gram$degree == gram_ideal, ]

print(wals_ideal)
print(gram_ideal)
```


# Mean distances

```{r}
mean(fullwals[fullwals$degree==1, ]$mean_distance)
mean(fullwals[fullwals$degree==wals_ideal, ]$mean_distance)
mean(fullwals[fullwals$degree==500, ]$mean_distance)
mean(fullgram[fullgram$degree==1, ]$mean_distance)
mean(fullgram[fullgram$degree==gram_ideal, ]$mean_distance)
mean(fullgram[fullgram$degree==500, ]$mean_distance)
```


# Basic model: comparison of $\Delta$ between typologies of different statuses

```{r}
basic_model <- function(data) {
	data$overattested <- data$Delta_over
	data$underattested <- data$Delta_under

	datah <- melt(data, id.vars=c("pair", "status", "abs_corrected_phi"), measure.vars=c("overattested", "underattested"))
	mod <- lm(value ~ variable*status, datah)
	
	emm <- emmeans(mod, specs = pairwise ~ variable:status)
	con <- as.data.frame(emm$contrasts)
	eff <- as.data.frame(eff_size(emm, sigma=sigma(mod), edf=mod$df, method="identity"))

	list(mod=mod, con=con, eff=eff)
}

mod_wals <- basic_model(wals)
mod_gram <- basic_model(gram)
```

## WALS results

```{r}
print(mod_wals$con)
print(mod_wals$eff)
```

## Grambank results

```{r}
print(mod_gram$con)
print(mod_gram$eff)
```


## Nice tables for paper

```{r}
mods = list(mod_wals, mod_gram)
names = list("wals", "grambank")

write_con <- function(mod, dataset) {
	#mod$con %>% dust %>% sprinkle(cols=c("estimate", "SE", "t.ratio"), round=4) %>% sprinkle(cols="p.value", fn=quote(pvalString_demo(value, stars=TRUE))) %>% write.table(file=paste0("../../results/tables/mod1_con_", dataset, ".csv"), row.names=FALSE, col.names=FALSE, sep=",", quote=FALSE)
	mod$con %>% subset(select=c("contrast", "estimate", "p.value")) %>% dust %>% sprinkle(cols=c("estimate", "SE", "t.ratio"), round=4) %>% sprinkle(cols="p.value", fn=quote(pvalString_demo(value, stars=TRUE))) %>% write.table(file=paste0("../../results/tables/mod1_con_", dataset, ".csv"), row.names=FALSE, col.names=FALSE, sep=",", quote=FALSE)
}

write_eff <- function(mod, dataset) {
	#mod$eff %>% dust %>% sprinkle(cols=c("effect.size", "SE", "lower.CL", "upper.CL"), round=3) %>% sprinkle(cols="p.value", fn=quote(pvalString_demo(value, stars=TRUE))) %>% write.table(file=paste0("../../results/tables/mod1_eff_", dataset, ".csv"), row.names=FALSE, col.names=FALSE, sep=",", quote=FALSE)
	mod$eff %>% subset(select=c("contrast", "effect.size", "lower.CL", "upper.CL")) %>% dust %>% sprinkle(cols=c("effect.size", "SE", "lower.CL", "upper.CL"), round=3) %>% sprinkle(cols="p.value", fn=quote(pvalString_demo(value, stars=TRUE))) %>% write.table(file=paste0("../../results/tables/mod1_eff_", dataset, ".csv"), row.names=FALSE, col.names=FALSE, sep=",", quote=FALSE)
}

write_combined <- function(mod, dataset) {
	df <- mod$con
	df$cohens.d <- mod$eff$effect.size
	df %>% subset(select=c("contrast", "estimate", "cohens.d", "p.value")) %>% dust %>% sprinkle(cols=c("estimate", "cohens.d"), round=4) %>% sprinkle(cols="p.value", fn=quote(pvalString_demo(value, stars=TRUE))) %>% write.table(file=paste0("../../results/tables/mod1_combined_", dataset, ".csv"), row.names=FALSE, col.names=FALSE, sep=",", quote=FALSE)
}

write_combined_concise <- function(mod, dataset) {
	df <- mod$con
	df$cohens.d <- mod$eff$effect.size

	df <- df[str_count(df$contrast, "underattested") == 2 | str_count(df$contrast, "overattested") == 2, ]
	df <- df[c(3,4,6,1,2,5), ]
	df %>% subset(select=c("contrast", "estimate", "cohens.d", "p.value")) %>% dust %>% sprinkle(cols=c("estimate", "cohens.d"), round=4) %>% sprinkle(cols="p.value", fn=quote(pvalString_demo(value, stars=TRUE))) %>% write.table(file=paste0("../../results/tables/mod1_combined_concise_", dataset, ".csv"), row.names=FALSE, col.names=FALSE, sep=",", quote=FALSE)
}

for (i in 1:2) {
	write_con(mods[[i]], names[[i]])
	write_eff(mods[[i]], names[[i]])
	write_combined(mods[[i]], names[[i]])
	write_combined_concise(mods[[i]], names[[i]])
}
```


## $\phi$ comparison

```{r}
comp <- merge(wals, gram, by="pair_ID")

g1 <- ggplot(comp, aes(x=abs_phi.x, y=abs_phi.y)) + geom_point() + geom_smooth(method=lm) + xlab("WALS") + ylab("Grambank") + xlim(0,1) + ylim(0,1) + ggtitle(expression("(a) Plain correlation coefficient"~phi)) + deftheme()
g2 <- ggplot(comp, aes(x=abs_corrected_phi.x, y=abs_corrected_phi.y)) + geom_point() + geom_smooth(method=lm) + xlab("WALS") + ylab("Grambank") + xlim(0,1) + ylim(0,1) + ggtitle(expression("(b) Corrected correlation coefficient"~phi[c])) + deftheme()

png(filename="../../results/plots/grambankwals.png", width=3000, height=1600, res=500)
grid.arrange(g1, g2, nrow=1)
dev.off()
```

